[phases.setup]
aptPkgs = [
  "libpango-1.0-0",
  "libpangoft2-1.0-0",
  "libpangocairo-1.0-0",
  "libgdk-pixbuf2.0-0",
  "libffi-dev",
  "libcairo2",
  "libglib2.0-0",
  "fonts-noto"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
