import type { Metadata } from "next";
import LegalPage, { LegalHeading } from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Terms of Service — CareerNeeti",
  description:
    "The terms on which CareerNeeti's career assessment and report are provided, including what the assessment is and is not.",
};

// See the note in privacy/page.tsx — these must be real values before publishing.
const ENTITY = "[registered entity name]";
const CONTACT_EMAIL = "[contact email]";

export default function TermsOfService() {
  return (
    <LegalPage title="Terms of Service" lastUpdated="2 September 2026">
      <p>
        These terms govern your use of CareerNeeti, operated by {ENTITY}. By taking the assessment
        you agree to them. If you are under 18, you may use the service only with the involvement of
        a parent or guardian.
      </p>

      <LegalHeading>What the service is</LegalHeading>
      <p>
        CareerNeeti provides a structured self-assessment covering interests, work values,
        self-efficacy, personality and optional aptitude, and produces a personalised report
        suggesting academic streams and career directions to explore.
      </p>

      <LegalHeading>What the assessment is not</LegalHeading>
      <p>
        This matters more than anything else on this page, so we state it plainly:
      </p>
      <ul className="list-disc pl-6 space-y-2">
        <li>
          It is an <strong>interest inventory</strong>, not a diagnostic or clinical instrument. It
          does not measure intelligence, and it does not diagnose anything.
        </li>
        <li>
          <strong>Interest is not the same as aptitude.</strong> Enjoying a kind of work does not by
          itself mean you will excel at it, and the report should be read with that in mind.
        </li>
        <li>
          Scores are expressed as a percentage of the maximum possible for each scale. They are
          <strong> not percentile ranks</strong> and do not compare you against a norm group.
        </li>
        <li>
          The narrative portion of the report is generated by an AI language model. It may contain
          errors. Figures such as salaries, fees, cut-offs and timelines are indicative only and
          must be verified against official sources before you rely on them.
        </li>
      </ul>

      <LegalHeading>The report is guidance, not advice</LegalHeading>
      <p>
        The report is intended to widen the set of options a student considers and to support a
        conversation with parents, teachers and counsellors. It is not professional educational,
        financial, psychological or career advice, and it should not be the sole basis for a
        decision about a student&rsquo;s education. Decisions taken on the basis of the report are
        your own.
      </p>

      <LegalHeading>Cost</LegalHeading>
      <p>
        <strong>On this website</strong>, the preliminary quiz is free. Where the full assessment
        is offered online without charge, that is stated at the point you start it.
      </p>
      <p>
        <strong>Through a school</strong>, CareerNeeti runs an in-person session and the school
        communicates the fee to parents in advance on a printed circular, along with what is
        included. Any fee is collected by arrangement with the school, not through this website.
        You will always be told the amount before you are asked to pay.
      </p>

      <LegalHeading>Acceptable use</LegalHeading>
      <p>
        Please answer honestly — the report is only as useful as the responses behind it. Do not
        attempt to disrupt the service, submit automated or bulk responses, or use it to collect
        data about other people without their knowledge.
      </p>

      <LegalHeading>Availability</LegalHeading>
      <p>
        The service is provided on an &ldquo;as is&rdquo; basis. We do not guarantee uninterrupted
        availability, and we may change or withdraw features. To the extent permitted by law, our
        liability arising from your use of the service is limited to the amount you paid us for it.
      </p>

      <LegalHeading>Your data</LegalHeading>
      <p>
        Our handling of personal data is described in the{" "}
        <a href="/privacy" className="text-secondary underline">Privacy Policy</a>, which forms part
        of these terms.
      </p>

      <LegalHeading>Governing law</LegalHeading>
      <p>
        These terms are governed by the laws of India, and the courts of India have exclusive
        jurisdiction over any dispute arising from them.
      </p>

      <LegalHeading>Contact</LegalHeading>
      <p>Questions about these terms: {CONTACT_EMAIL}</p>
    </LegalPage>
  );
}
