"""lead token

Revision ID: 59b5664374a7
Revises: dcf79f1f64db
Create Date: 2026-08-24 11:18:14.815171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b5664374a7'
down_revision: Union[str, Sequence[str], None] = 'dcf79f1f64db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('token', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_leads_token'), 'leads', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_token'), table_name='leads')
    op.drop_column('leads', 'token')
    # ### end Alembic commands ###
