"""school soft delete

Revision ID: 606bcfa6a02f
Revises: ae611820d91d
Create Date: 2026-08-24 11:00:27.491245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '606bcfa6a02f'
down_revision: Union[str, Sequence[str], None] = 'ae611820d91d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required: adding a NOT NULL column to a table that
    # already has rows fails outright without one (NotNullViolation). It is then
    # dropped so the column's default lives in the model, not the schema.
    op.add_column(
        'schools',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column('schools', 'is_active', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'is_active')
    # ### end Alembic commands ###
