"""baseline schema

Revision ID: ae611820d91d
Revises: 
Create Date: 2026-08-17 17:02:33.139221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae611820d91d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('class_level', sa.Integer(), nullable=True),
    sa.Column('holland_code', sa.String(length=6), nullable=True),
    sa.Column('recommended_stream', sa.String(length=100), nullable=True),
    sa.Column('riasec_scores', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('converted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('board', sa.String(length=20), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schools')),
    sa.UniqueConstraint('code', name=op.f('uq_schools_code'))
    )
    op.create_index(op.f('ix_schools_id'), 'schools', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_users_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('school_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('counsellor_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['counsellor_id'], ['users.id'], name=op.f('fk_school_assignments_counsellor_id_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_school_assignments_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_school_assignments'))
    )
    op.create_index(op.f('ix_school_assignments_id'), 'school_assignments', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('classes_assessed', sa.JSON(), nullable=True),
    sa.Column('counsellor_name', sa.String(length=255), nullable=True),
    sa.Column('counsellor_certification', sa.String(length=255), nullable=True),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('opt_in_students', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('llm_provider', sa.String(length=20), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('generation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_sessions_created_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_sessions_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_table('counsellor_commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('counsellor_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('students_count', sa.Integer(), nullable=True),
    sa.Column('rate_per_student', sa.Integer(), nullable=True),
    sa.Column('amount_inr', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['counsellor_id'], ['users.id'], name=op.f('fk_counsellor_commissions_counsellor_id_users')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_counsellor_commissions_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_counsellor_commissions'))
    )
    op.create_index(op.f('ix_counsellor_commissions_id'), 'counsellor_commissions', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id_external', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('class_level', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('parent_name', sa.String(length=255), nullable=True),
    sa.Column('parent_phone', sa.String(length=15), nullable=True),
    sa.Column('family_income', sa.String(length=20), nullable=True),
    sa.Column('location_type', sa.String(length=20), nullable=True),
    sa.Column('parental_education', sa.String(length=20), nullable=True),
    sa.Column('first_gen_learner', sa.Boolean(), nullable=True),
    sa.Column('self_efficacy', sa.JSON(), nullable=True),
    sa.Column('riasec_raw_responses', sa.JSON(), nullable=True),
    sa.Column('riasec_scores', sa.JSON(), nullable=True),
    sa.Column('holland_code', sa.String(length=6), nullable=True),
    sa.Column('work_values', sa.JSON(), nullable=True),
    sa.Column('matched_careers', sa.JSON(), nullable=True),
    sa.Column('academic_marks', sa.JSON(), nullable=True),
    sa.Column('coaching_affordability', sa.String(length=20), nullable=True),
    sa.Column('mobility_willingness', sa.String(length=20), nullable=True),
    sa.Column('parent_primary_concern', sa.String(length=30), nullable=True),
    sa.Column('family_career_role_model', sa.String(length=100), nullable=True),
    sa.Column('aptitude_raw_responses', sa.JSON(), nullable=True),
    sa.Column('aptitude_scores', sa.JSON(), nullable=True),
    sa.Column('aptitude_time_taken', sa.Integer(), nullable=True),
    sa.Column('tipi_raw_responses', sa.JSON(), nullable=True),
    sa.Column('big_five_scores', sa.JSON(), nullable=True),
    sa.Column('career_readiness_responses', sa.JSON(), nullable=True),
    sa.Column('career_readiness_score', sa.Integer(), nullable=True),
    sa.Column('career_readiness_level', sa.String(length=20), nullable=True),
    sa.Column('stream_pref_parent', sa.String(length=50), nullable=True),
    sa.Column('stream_pref_student', sa.String(length=50), nullable=True),
    sa.Column('career_concern', sa.String(length=100), nullable=True),
    sa.Column('report_content', sa.JSON(), nullable=True),
    sa.Column('report_status', sa.String(length=20), nullable=True),
    sa.Column('qa_flags', sa.JSON(), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('report_token', sa.String(length=64), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), nullable=True),
    sa.Column('delivery_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('helpline_booked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_obtained', sa.Boolean(), nullable=True),
    sa.Column('consent_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_parent_name', sa.String(length=255), nullable=True),
    sa.Column('consent_method', sa.String(length=20), nullable=True),
    sa.Column('llm_cost', sa.Float(), nullable=True),
    sa.Column('d2c_assessment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_students_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students'))
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_report_token'), 'students', ['report_token'], unique=True)
    op.create_table('d2c_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('student_name', sa.String(length=255), nullable=True),
    sa.Column('student_email', sa.String(length=255), nullable=True),
    sa.Column('parent_phone', sa.String(length=15), nullable=True),
    sa.Column('class_level', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('amount_inr', sa.Integer(), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('raw_responses', sa.JSON(), nullable=True),
    sa.Column('self_efficacy', sa.JSON(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('family_income', sa.String(length=20), nullable=True),
    sa.Column('location_type', sa.String(length=20), nullable=True),
    sa.Column('parental_education', sa.String(length=20), nullable=True),
    sa.Column('first_gen_learner', sa.Boolean(), nullable=True),
    sa.Column('academic_marks', sa.JSON(), nullable=True),
    sa.Column('coaching_affordability', sa.String(length=20), nullable=True),
    sa.Column('mobility_willingness', sa.String(length=20), nullable=True),
    sa.Column('parent_primary_concern', sa.String(length=30), nullable=True),
    sa.Column('family_career_role_model', sa.String(length=100), nullable=True),
    sa.Column('aptitude_raw_responses', sa.JSON(), nullable=True),
    sa.Column('aptitude_scores', sa.JSON(), nullable=True),
    sa.Column('aptitude_time_taken', sa.Integer(), nullable=True),
    sa.Column('tipi_raw_responses', sa.JSON(), nullable=True),
    sa.Column('big_five_scores', sa.JSON(), nullable=True),
    sa.Column('career_readiness_responses', sa.JSON(), nullable=True),
    sa.Column('career_readiness_score', sa.Integer(), nullable=True),
    sa.Column('career_readiness_level', sa.String(length=20), nullable=True),
    sa.Column('report_email_sent', sa.Boolean(), nullable=True),
    sa.Column('report_whatsapp_sent', sa.Boolean(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_d2c_assessments_lead_id_leads')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_d2c_assessments_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_d2c_assessments'))
    )
    op.create_index(op.f('ix_d2c_assessments_id'), 'd2c_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_d2c_assessments_token'), 'd2c_assessments', ['token'], unique=True)
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('recommendation_match', sa.Boolean(), nullable=True),
    sa.Column('most_useful', sa.Text(), nullable=True),
    sa.Column('missing', sa.Text(), nullable=True),
    sa.Column('would_recommend', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_feedback_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_table('student_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('actual_stream_chosen', sa.String(length=100), nullable=True),
    sa.Column('actual_career_interest', sa.String(length=255), nullable=True),
    sa.Column('recommendation_matched', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('collected_via', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_student_outcomes_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_outcomes')),
    sa.UniqueConstraint('student_id', name=op.f('uq_student_outcomes_student_id'))
    )
    op.create_index(op.f('ix_student_outcomes_id'), 'student_outcomes', ['id'], unique=False)
    # students.d2c_assessment_id <-> d2c_assessments.student_id is a foreign-key
    # cycle, so this side is added after both tables exist. It is written out by
    # hand because op.create_table() silently DISCARDS a use_alter constraint
    # rather than deferring it -- the emitted DDL had no such constraint at all.
    # SQLite (local dev) cannot ALTER a table to add a constraint, and does not
    # enforce foreign keys unless PRAGMA foreign_keys=ON. The column exists
    # either way; only Postgres gets the actual constraint.
    if op.get_bind().dialect.name != 'sqlite':
        op.create_foreign_key(
            'fk_students_d2c_assessment_id_d2c_assessments',
            'students', 'd2c_assessments',
            ['d2c_assessment_id'], ['id'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name != 'sqlite':
        op.drop_constraint(
            'fk_students_d2c_assessment_id_d2c_assessments', 'students', type_='foreignkey'
        )
    op.drop_index(op.f('ix_student_outcomes_id'), table_name='student_outcomes')
    op.drop_table('student_outcomes')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_d2c_assessments_token'), table_name='d2c_assessments')
    op.drop_index(op.f('ix_d2c_assessments_id'), table_name='d2c_assessments')
    op.drop_table('d2c_assessments')
    op.drop_index(op.f('ix_students_report_token'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_counsellor_commissions_id'), table_name='counsellor_commissions')
    op.drop_table('counsellor_commissions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_school_assignments_id'), table_name='school_assignments')
    op.drop_table('school_assignments')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_schools_id'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
