"""persist d2c stream recommendation

Revision ID: dcf79f1f64db
Revises: 606bcfa6a02f
Create Date: 2026-08-24 11:10:14.076295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcf79f1f64db'
down_revision: Union[str, Sequence[str], None] = '606bcfa6a02f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('d2c_assessments', sa.Column('stream_recommendation', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('d2c_assessments', 'stream_recommendation')
    # ### end Alembic commands ###
